import { StyleSheet } from "react-native";
import { C } from "../components/Theme";

export const s = StyleSheet.create({
  center: { flex: 1, backgroundColor: C.card, alignItems: "center", justifyContent: "center", padding: 16 },
  h1: { color: C.text, fontSize: 22, fontWeight: "800" },
  dim: { color: C.dim },
  header: { height: 56, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, borderBottomColor: C.border, borderBottomWidth: 1, backgroundColor: C.bg },
  headerTitle: { color: C.text, fontSize: 18, fontWeight: "700" },
  communityCard: { flexDirection: "row", alignItems: "center", backgroundColor: C.card, padding: 12, borderBottomColor: C.border, borderBottomWidth: 1 },
  deleteBtn: { borderWidth: 1, borderColor: "#D14B4B", paddingVertical: 14, alignItems: "center", borderRadius: 12, backgroundColor: "transparent" },
  menuRow: { paddingHorizontal: 16, paddingVertical: 14, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomColor: C.border, borderBottomWidth: 1, backgroundColor: C.card },
  menuText: { color: C.text, fontSize: 16 },
  label: { color: C.text, marginTop: 10, marginBottom: 6 },
  input: { backgroundColor: "#101317", color: C.text, borderColor: C.border, borderWidth: 1, borderRadius: 12, padding: 12 },
  select: { backgroundColor: "#101317", borderColor: C.border, borderWidth: 1, borderRadius: 12, padding: 12 },
  uploadBox: { height: 90, borderRadius: 12, borderWidth: 1, borderColor: C.border, backgroundColor: "#101317", marginBottom: 14, alignItems: "center", justifyContent: "center" },
  cardBox: { margin: 16, borderRadius: 16, overflow: "hidden", borderColor: C.border, borderWidth: 1, backgroundColor: C.card },
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: C.border },
  choice: { borderColor: C.border, borderWidth: 1, borderRadius: 12, padding: 14, marginBottom: 10, backgroundColor: C.card },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.6)", justifyContent: "center", alignItems: "center", padding: 20 },
  modalCard: { backgroundColor: "#1b1f27", borderRadius: 18, padding: 18, borderColor: "#2a2f38", borderWidth: 1, width: "100%" },
  drawerItem: { flexDirection: "row", alignItems: "center", paddingVertical: 14, paddingHorizontal: 16, borderBottomColor: C.border, borderBottomWidth: 1 },
  sectionLabelWrap: { paddingHorizontal: 16, paddingTop: 14, backgroundColor: C.card2 },
  sectionLabel: { color: C.dim, fontSize: 12, textTransform: "uppercase", letterSpacing: 1 },
  roomRow: { paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderColor: C.border, backgroundColor: C.card, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  grid2: { flexDirection: "row", flexWrap: "wrap", paddingHorizontal: 16, gap: 12, marginBottom: 12 },
  statCard: { width: "47%", backgroundColor: "#101317", borderWidth: 1, borderColor: C.border, borderRadius: 14, paddingVertical: 18, paddingHorizontal: 10 },
  folderRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 16, borderBottomColor: C.border, borderBottomWidth: 1 },
  folderIcon: { width: 44, height: 44, borderRadius: 10, backgroundColor: "#20242b", marginRight: 12, borderWidth: 1, borderColor: C.border },
  addDashed: { borderWidth: 1, borderStyle: "dashed", borderColor: C.dim, borderRadius: 12, alignItems: "center", justifyContent: "center", paddingVertical: 16 },
  addBox: { borderWidth: 1, borderStyle: "dashed", borderColor: C.dim, borderRadius: 12, alignItems: "center", justifyContent: "center", paddingVertical: 16, backgroundColor: "#0f1217" },
  addCircle: { width: 58, height: 58, borderRadius: 29, borderColor: C.dim, borderWidth: 1, borderStyle: "dashed", alignItems: "center", justifyContent: "center" },
  drop: { borderWidth: 1, borderColor: C.border, borderRadius: 14, padding: 12, backgroundColor: "#101317", marginBottom: 12 },
  badge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, alignSelf: "flex-start" },
  titleRow: { paddingHorizontal: 16, paddingVertical: 16, borderBottomColor: C.border, borderBottomWidth: 1, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  previewRow: { flexDirection: "row", gap: 12, marginBottom: 16 },
  previewCard: { flex: 1, height: 160, borderRadius: 16, borderWidth: 1, borderColor: C.border, backgroundColor: "#0f1217", alignItems: "center", justifyContent: "center" },
});
